### PR TITLE
Save/load index to files, improve logging

### LINKED ISSUE #62: [Feature request] Store notes cache index to the file to avoid reparsing
**Is your feature request related to a problem? Please describe.**

I have a big vault with ~40k notes. Recreating an index on each Obsidian open is an unnecessary massive heavy operation.

**Describe the solution you'd like**

I suggest to store cache index to the external file so it could be imported without reindexing all the notes. Probably there should be some additional mechanism to catch notes changed since cache index was saved. It could be just notes last modified date.

**Describe alternatives you've considered**

[Everything 1.5](https://www.voidtools.com/forum/viewtopic.php?f=12&t=9793)

**Additional context**

N/A

### PR DESCRIPTION
**Pull request by mnaoumov**
Fixes #62

### CODE REVIEW

**Comment by mnaoumov** [comment]
@scambier ready

**Comment by scambier** [comment]
Looks good, thanks again. I'll make a first beta release this week :)

**Comment by scambier** [comment]
@mnaoumov I forgot to ask the most important question: how are the performances after this PR?

**Comment by mnaoumov** [comment]
@scambier the performance improved greatly. My vault is pretty big

`searchIndex.json` - 39 Mb
`notesCache.json` - 55 Mb

Preloading them saves tons of startup time.

And this is especially extremely performant on mobile

**Pull request merged**
