### PR TITLE
[Minor Feature] Ignore index and cache files in git on user side by default

### PR DESCRIPTION
**Pull request by GollyTicker**
Thanks for the amazing plugin. I like it and use it a lot. However, I stumbled upon some caching/indexing issues, which had happend, because file file was erronously in git VCS.

Currently, the files `historyCache.json`, `searchIndex.json`, etc. are generated in the plugin folder on the user side (if they made the setting of storing them on the filesystem):

image

The problem is, that it's not clear which files should be added to the `.gitignore`. Many users may even not know the details or read everything. They might miss, that these files should be ignored. This even happend to me. I had `searchIndex.json` added t m .gitignore - but lateron the file `historyCache.json` was created by omnisearch. Since I didn't look into the plugin folder again, it was synchronized as well.

Why can't we just have these files ignored by default?
In this PR I just added a small .gitignore as part of the release, which should ensure, that the files are not synchronized.
Even for advanced git users, it's really not clear upfront which files should be ignored, even if they knew how to do that.

However, you might have different perspectives. So please let me know, if I missed something.
Since you wrote "...files must not be syncrhonized.", it makes sense, to automatically ignore them.

What do you think about all of this?

Ideally, other version control systems should be supported as well. If you don't want these files to be in the final release, then I'm not sure how we can make it clear to the user, that they should exclude certain files from VCS.

---
I wanted to test, if and how the .gitignore is added to the release archive. However, I was not able to get `npm run build` working after installing rustup and wasm-pack. It was just hanging and not progressing...

---
I am aware, that I created this PR before creating an issue. But since it's just a minor thing, I went ahead and directly made a PR.
I hope that is okay for you.

### CODE REVIEW

**Comment by scambier** [comment]
Hey thanks for your PR :)

Can you just add `*.data` to the list? In the very short term (next non-beta release), the cache files are going to be [these](https://github.com/scambier/obsidian-omnisearch/blob/master/src/globals.ts#L15-L18).

Once PDF indexing is stable, I'm also going to remove those files entirely and will probably use IndexedDB to store the cache. Just so you know, because I'll probably have to delete the (soon useless) .gitignore :)

**Comment by GollyTicker** [comment]
Thanks for the quick response!

Great, I'll edit the .gitignore whenever I'm back home.

If you want, you can also just add the line and merge the PR. Until the IndexedDB is used, this gitignore will be useful.

**Comment by GollyTicker** [comment]
I updated it. Shall I merge this now? Otherwise you can also go ahead and merge it.

**Comment by GollyTicker** [comment]
I also added it to the release process now. I cannot test the release process though.

**Comment by scambier** [comment]
I'll check the release and fix it if necessary

**Pull request merged**
